apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: post-action-failed
spec:
  serviceAccountName: promotion-template
  arguments:
    parameters:
    - name: APP_NAME
    # - name: COMMIT_SHA
  entrypoint: echo-post-action-failed
  templates:
  - name: echo-post-action-failed
    script:
      image: alpine
      command:
      - sh
      source: |
        echo "synced app {{ workflow.parameters.APP_NAME }}"
        # exit 1
        # sleep 60
  # - name: echo1
  #   script:
  #     image: alpine
  #     command:
  #     - sh
  #     source: |
  #       echo "synced app {{ workflow.parameters.APP_NAME }}"
        
        
