apiVersion: codefresh.io/v1beta1
kind: PromotionTemplate
metadata:
  name: promotion-template
spec:
  applicationSourceSelector:
    matchExpressions:
      - key: codefresh.io/product
        operator: Exists
  priority: 0
  versionSource:
    file: Chart.yaml
    jsonPath: appVersion
  promotion:
    guestbook-ui-deployment.yaml:
      jsonPaths:
        - $..image
    Chart.yaml:
      jsonPaths:
        - appVersion
    version.json:
      jsonPaths:
        - $.Application.Version
